name    'torian-ldap'
version '0.1.2'
source 'https://github.com/torian/puppet-ldap'
author 'Emiliano Castagnari ecastag@gmail.com (aka Torian)'
license 'Apache'
summary 'OpenLDAP module for Puppet.'
description 'Manage OpenLDAP clients and server via Puppet'
project_page 'https://github.com/torian/puppet-ldap'
