name    'torian-ldap'
version '0.0.1'
source 'https://github.com/torian/puppet-ldap'
author 'torian'
license 'Copyleft (C) 2012 Emiliano Castagnari ecastag@gmail.com (a.k.a. Torian)'
summary 'OpenLDAP module for Puppet.'
description 'Managa OpenLDAP clients and server via Puppet'
project_page 'https://github.com/torian/puppet-ldap'
